spring:
  profiles:
    active: test
  application:
    name: consumer
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
server:
  port: 8081
  servlet:
    context-path: /consumer
login:
  types:
    pwd: pwdLogin
    qq: qqLogin
    weixin: weixinLogin
