spring:
  profiles:
    active: test
  application:
    name: consumer
server:
  port: 8081
  servlet:
    context-path: /consumer
login:
  types:
    pwd: pwdLogin
    qq: qqLogin
    weixin: weixinLogin